[versions]
ksp = "2.3.1"
android = "8.13.0"
material = "1.13.0"
androidx-appcompat = "1.7.1"
androidx-core-ktx = "1.17.0"
androidx-fragment-ktx = "1.8.9"
androidx-recyclerview = "1.4.0"
androidx-lifecycle-runtime-ktx = "2.9.4"
android-navigation = "2.9.5"
compose-bom = "2025.11.00"
compose-activity = "1.11.0"
hilt = "2.57.2"
moshi = "1.15.2"
retrofit = "3.0.0"
opensource-licenses = "17.3.0"
kotlinx-coroutines = "1.10.2"
test-junit = "4.13.2"
test-hamcrest = "3.0"
test-mockk = "1.14.6"
test-mockito = "5.20.0"
test-mockito-kotlin = "6.1.0"
test-mockito-android = "2.28.6"
test-konsist = "0.17.3"
test-android-espresso = "3.7.0"
test-androidx-junit = "1.3.0"
test-androidx-rules = "1.7.0"
androidx-tracing = "1.3.0"
uiautomator = "2.3.0"
okhttp3 = "5.3.0"
kotlin = "2.2.21"
plugin-oss-licenses = "0.10.9"
ktlint = "13.1.0"
detekt = "1.23.8"
kotlinx-serialization-json = "1.9.0"
minSdk = "23"
targetSdk = "36"
compileSdk = "36"

[libraries]
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment-ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
test-androidx-junit = { module = "androidx.test.ext:junit", version.ref = "test-androidx-junit" }
androidx-tracing = { module = "androidx.tracing:tracing", version.ref = "androidx-tracing" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime-ktx" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "android-navigation" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-interceptor-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }
opensource-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "opensource-licenses" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
test-kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
test-junit = { module = "junit:junit", version.ref = "test-junit" }
test-hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "test-hamcrest" }
test-mockk = { module = "io.mockk:mockk", version.ref = "test-mockk" }
test-mockito = { module = "org.mockito:mockito-core", version.ref = "test-mockito" }
test-mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "test-mockito-kotlin" }
test-mockito-android = { module = "com.linkedin.dexmaker:dexmaker-mockito-inline", version.ref = "test-mockito-android" }
test-konsist = { module = "com.lemonappdev:konsist", version.ref = "test-konsist" }
test-android-hilt = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
test-android-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
test-android-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp3" }
test-androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "test-android-espresso" }
test-androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "test-android-espresso" }
test-androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "test-android-espresso" }
test-androidx-rules = { module = "androidx.test:rules", version.ref = "test-androidx-rules" }
test-compose-ui-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
debug-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
debug-compose-ui-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "android-navigation" }
plugin-oss-licenses = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "plugin-oss-licenses" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

[bundles]
compose = ["compose-ui", "compose-ui-graphics", "compose-ui-tooling-preview", "compose-material3", "compose-activity", "compose-navigation"]
retrofit = ["retrofit", "retrofit-converter-moshi", "retrofit-interceptor-logging"]

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization",version.ref = "kotlin" }
